name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  POSTGRES_URL: postgresql://prisma:prisma@localhost:5433/tests

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - uses: ./.github/actions/docker-compose
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: pnpm run test
